config/routes.rb
Rails.application.routes.draw do
  devise_for :org_people, :controllers => { 
    :registrations => "org_people/registrations",
    :sessions => "org_people/sessions",
    :passwords => "org_people/passwords" , 
    :confirmations => "org_people/confirmations" }
    
  devise_scope :org_people do
    get 'signup', to: 'org_people/registrations#new'
    get 'signin', to: 'org_people/sessions#new'
    delete 'signout', to: 'org_people/sessions#destroy'
  end
  root to: 'catalogues#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :catalogues
  resources :org_people
end

app/models/org_company.rb
class OrgCompany < ApplicationRecord
  has_and_belong_to_many :org_contacts
  has_many  :org_persons
  has_many :org_products
  belongs_to :typ_company, foreign_key: "typ_company_id"
end

app/models/org_contact.rb
class OrgContact < ApplicationRecord
  belongs_to :org_person, foreign_key: "org_person_id"
  belongs_to :org_company, foreign_key: "org_company_id"
  belongs_to :typ_contact, foreign_key: "typ_contact_id"
  belongs_to :typ_country, foreign_key: "typ_country_id"
  belongs_to :typ_region, foreign_key: "typ_region_id"
end

app/models/org_person.rb
class OrgPerson < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :org_contacts
  belongs_to :org_company, foreign_key:"org_company_id"
  belongs_to :typ_position, foreign_key:"typ_position_id"
  accepts_nested_attributes_for :org_contacts
end

app/models/org_product.rb
class OrgProduct < ApplicationRecord
  belongs_to :org_company, foreign_key: "org_company_id"
  belongs_to :typ_category, foreign_key: "typ_category_id"
  belongs_to :typ_subcategory, foreign_key: "typ_subcategory_id"
end

app/models/trx_order.rb
class TrxOrder < ApplicationRecord
  has_many :TrxOrderItem
  has_many :TrxOrderFee
end

app/models/trx_order_fee.rb
class TrxOrderFee < ApplicationRecord
  belongs_to :TrxOrder, foreign_key: "trx_order_id"
end

app/models/trx_order_item.rb
class TrxOrderItem < ApplicationRecord
  belongs_to :org_company, foreign_key: "org_company_id"
  belongs_to :TrxOrder, foreign_key: "trx_order_id"
  belongs_to :OrgProduct, foreign_key: "org_product_id"
  belongs_to :ShippingAddress, foreign_key: "shipping_address_id"
end

app/models/typ_category.rb
class TypCategory < ApplicationRecord
  has_many :org_products
  has_many :typ_subcategory
end

app/models/typ_company.rb
class TypCompany < ApplicationRecord
  has_many :org_companies
end

app/models/typ_contact.rb
class TypContact < ApplicationRecord
  has_many :org_contacts
end

app/models/typ_country.rb
class TypCountry < ApplicationRecord
  has_many :org_contact
  has_many :typ_region
end

app/models/typ_fee.rb
class TypFee < ApplicationRecord
  has_many :TrxOrderFee
end

app/models/typ_position.rb
class TypPosition < ApplicationRecord
  has_many :org_people
end

app/models/typ_region.rb
class TypRegion < ApplicationRecord
  belongs_to :typ_country, foreign_key: "typ_country_id"
  has_many :org_contacts
  has_many :typ_sales_taxes
end

app/models/typ_sales_tax.rb
class TypSalesTax < ApplicationRecord
  belongs_to :typ_region, foreign_key: "typ_region_id"
  belongs_to :typ_tax, foreign_key: "typ_tax_id"
end

app/models/typ_subcategory.rb
class TypSubcategory < ApplicationRecord
  belongs_to :typ_category, foreign_key: "typ_category_id"
  has_many :org_products
end

app/models/typ_tax.rb
class TypTax < ApplicationRecord
  has_many :typ_sales_taxes
end

app/helpers/catalogues_helper.rb
module CataloguesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?
    messages = resource.errors.full_messages.map{ |msg| content_tag(:li, msg)}.join
    sentence = I18n.t("errors.messages.not_saved", count: resource.errors.count, resource: resource.class.model_name.human.downcase)
    html = <<-HTML
    <div class="alert alert-danger">
      #{sentence}
    </div>
    <div class="alert-error alert-block register_error">
      #{messages}
    </div>
    HTML
    html.html_safe
  end
end

app/helpers/org_people_helper.rb
module OrgPeopleHelper
end

app/views/layouts/_contactfields.html.erb
<%= f.fields_for :org_contacts do |contact|%>
  
  <% if !@contactInfo["avatar"].blank? %>
    <%= image_tag @contactInfo.avatar_url(:medium).to_s, :class=>"profilePhoto" %>
  <% end %>
  <div class="photoPreview">
    <i class="fa fa-upload photoUpload"></i>
    <p id="uploadClick">Click to Upload</p>
  </div>
    
  <%= contact.file_field :avatar, accept: 'image/png,image/gif,image/jpeg, image/jpg', id: 'uploadAvatar' %>
  <p class="deletePhoto">Delete</p>

  <%= contact.text_field :address1, placeholder: "Address 1", :class => "form-control" %>
  <%= contact.text_field :address2, placeholder: "Address 2", :class => "form-control" %>
  <%= contact.text_field :city, placeholder: "City", :class => "form-control" %>
  <%= contact.fields_for :typ_countries do |country|%>
      <%= country.collection_select :id, TypCountry.order(:country),:id,:country, {prompt: "Please Select Country", selected: @contactInfo["typ_country_id"] }, {:class => "form-control"} %>
  <% end %>
  <%= contact.fields_for :typ_regions do |region|%>
    <%= region.grouped_collection_select :id, TypCountry.order(:country),:typ_region, :country, :id, :name, {prompt: "Please Select Region", selected: @contactInfo["typ_region_id"] }, {:class => "form-control"}%>
  <% end %>
  <%= contact.fields_for :org_company do |company|%>
    <%= company.collection_select :id, OrgCompany.order(:name),:id,:name, {prompt: "Please Select Company", selected: @contactInfo["org_company_id"] }, {:class => "form-control"} %>
  <% end %>
  <%= contact.text_field :postal_code, placeholder: "Postal Code", :class => "form-control" %>
  <%= contact.text_field :email, placeholder: "Email", :class => "form-control", readonly: true %>
  <%= contact.text_field :business_number, placeholder: "Business Number", :class => "form-control" %>
  <%= contact.text_field :cell_number, placeholder: "Cell Number", :class => "form-control" %>
  <%= contact.hidden_field :org_person_id, value: current_org_person.id %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="card text-center navbar-fixed-bottom">
  <div class="card-footer text-muted">
    <div class="container">
      <nav>
        <ul>
          <!-- <li><%= link_to "About",   '#' %></li> -->
          <!-- <li><%= link_to "Fee Guide", '#' %></li> -->
          <li><%= link_to "Contact Us", "#" %></li>
          <li><%= link_to "Terms of Use",   "#" %></li>
          <li><%= link_to "Privacy Policy",   "#" %></li>
          <li><%= link_to "How it Works?",   "#" %></li>
        </ul>
      </nav>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <div class="form-inline my-2 my-lg-0">
      <% if !signed_in? %>
        <div class="navbar-right">
          <!-- <a href="" class="btn btn-default navbar-btn">login</a> -->
          <%= link_to "Login", new_org_person_session_path, class: "btn btn-default navbar-btn" %>
          <!-- <a href="" class="btn btn-primary navbar-btn">Register</a> -->
          <%= link_to "Register", new_org_person_registration_path, class: "btn btn-primary navbar-btn" %>
        </div>
      <% else %>
        <ul class="nav navbar-right navbar-btn">
          <li class="dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown<span class="caret"></span></a>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <li>
                <!-- <a class="dropdown-item" href="#">Profile</a> -->
                <%= link_to "Profile", edit_org_people_path(current_org_person.id), class: "dropdown-item" %>  
              </li>
              <li>
                <!-- <a class="dropdown-item" href="#">Logout</a> -->
                <%= link_to "Logout", destroy_org_people_session_path, method: :delete, class: "dropdown-item" %> 
              </li>
            </ul>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

<!-- <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%#= link_to "My Contact", root_path, class: "navbar-brand text-uppercase" %>
    </div> -->

    <!-- /.navbar-header -->

    <!-- <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Dashboard</a></li>
        <li><a href="#">All Contacts</a></li>
      </ul>
      <%# if !signed_in? %>
        <div class="navbar-right">
          <a href="" class="btn btn-default navbar-btn">login</a>
          <%#= link_to "Login", new_org_person_session_path, class: "btn btn-default navbar-btn" %>
          <a href="" class="btn btn-primary navbar-btn">Register</a>
          <%#= link_to "Register", new_org_person_registration_path, class: "btn btn-primary navbar-btn" %>
        </div>
      <%# else %>
        <ul class="nav navbar-right navbar-btn">
          <li class="dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown<span class="caret"></span></a>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <li>
                <a class="dropdown-item" href="#">Profile</a>
                <%#= link_to "Profile", edit_org_people_registration_path %>  
              </li>
              <li>
                <a class="dropdown-item" href="#">Logout</a>
                <%#= link_to "Logout", destroy_org_people_session_path, method: :delete %> 
              </li>
            </ul>
          </li>
        </ul>
        <div class="nav navbar-right navbar-btn">
          <%#= link_to new_contact_path, class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-plus"></i>
              Add Contact
          <%# end %>
        </div>
        <%#= render 'layouts/search_form' %>
      <%# end %>
    </div>
  </div>
</nav> -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ShoppingCart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% render 'layouts/shim' %>
  </head>

  <body class="<%= controller_name %> <%= action_name%>">
    <%= render 'layouts/header' %>

    <div class="container-fluid">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> col-md-8 col-md-offset-2 main"><%= value %></div>
    <% end %>
    <div class="row">
      <%= yield :sidebar %>
      <%= yield %>
    </div>
  </div>
  <%= render 'layouts/footer' %>
  <% debug(params) if Rails.env.development? %> 
    
  </body>
</html>

app/views/shared/_error_messages.html.erb
<%if @person %>
  <% if @person.errors.any? %>
    <div id="error_explanation" class="col-md-12">
      <div class="alert alert-danger" role="alert">
        The form contains <%= pluralize(@person.errors.count, "error") %>.
      </div>
      <ul>
        <% @person.errors.each do |attr, msg| %>
        <li>* <%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>